concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: clone
    - name: main
      run: |
        curl -L https://nixos.org/nix/install | sh
        source ~/.nix-profile/etc/profile.d/nix.sh

        sudo apt install jq

        set -x
        src=https://github.com/nixos/nixpkgs
        git clone --branch master --single-branch $src src
        mkdir -p data/nixpkgs
        git -C src log --format=%H > tmp
        jq -erRS [inputs] < tmp > data/nixpkgs/commits.json
    - name: commit
      run: |
        bash .github/workflows/push.sh "feat(conf): nixpkgs commits" data
