concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}
on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '0 */6 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: clone
    - name: main
      run: bash .github/workflows/nixpkgs-commits.sh
