concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 * * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: clone
    - name: main
      run: |
        bash .github/workflows/update-nixpkgs.commit.sh
    - name: commit
      run: |
        bash .github/workflows/push.sh "feat(conf): fetch nixpkgs commit" data
