concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 * * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: clone
    - name: main
      run: |
        curl -L https://nixos.org/nix/install | sh
        source ~/.nix-profile/etc/profile.d/nix.sh
        nix-env -iA nixpkgs.nixUnstable

        set -x
        nix --experimental-features 'flakes nix-command' build --no-pure-eval .#nixpkgs
        mkdir -p data/nixpkgs/commits
        cp -rLT result/* .
    - name: commit
      run: |
        set -x
        git config user.name 'Kevin Amado'
        git config user.email kamadorueda@gmail.com
        git pull --autostash --progress --rebase --stat origin main
        git add data
        git commit -m "feat(conf): update nixpkgs commits" --allow-empty
        git push
